
server:
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  application:
    name: edms-backend

---
spring:
  profiles: dev
  datasource:
    hikari:
      maximum-pool-size: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edmsSQL?useSSL=false&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: abcd@1234
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 50
        max-idle: 50
        min-idle: 5
        max-wait: 6000
    timeout: 10000
    database: 0

logging:
  level:
    org.springframework.web: INFO

server:
  port: 9770

file:
  static: /static/
  absolute: D:\files\
